### ISSUE TITLE
pre-commit fails with pylama: 'bool' is not iterable

### ISSUE THREAD

**Issue by cbm755** [johannesjh/req2flatpak#44]
I'm on Fedora.  I did:
  - `dnf install poetry` (never used this before, I know its probably better, etc etc but I'm slow to adopt new things)
  - `dnf install pre-commit`.  
  - then I did the instructions here: https://johannesjh.github.io/req2flatpak/main/development.html#ensuring-code-quality

1.  I tried `pre-commit run --all` and after recent commits on `main`, this works:

```
pre-commit run --all
poetry-check.............................................................Passed
poetry-lock..............................................................Passed
Sync with Poetry.........................................................Passed
isort (python)...........................................................Passed
black....................................................................Passed
prettier.................................................................Passed
rstcheck.................................................................Passed
pylama...................................................................Failed
- hook id: pylama
- exit code: 1

Executable `pylama` not found

bandit...................................................................Passed
```

Nice!

Except `pylama` is missing.  So I `pip install pylama`.  This gave me 8.4.1.

Try again:
```
pre-commit run --all
poetry-check.............................................................Passed
poetry-lock..............................................................Passed
Sync with Poetry.........................................................Passed
isort (python)...........................................................Passed
black....................................................................Passed
prettier.................................................................Passed
rstcheck.................................................................Passed
pylama...................................................................Failed
- hook id: pylama
- exit code: 1

Traceback (most recent call last):
  File "/home/cbm/.local/bin/pylama", line 8, in <module>
    sys.exit(shell())
             ^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/main.py", line 115, in shell
    errors = check_paths(
             ^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/main.py", line 68, in check_paths
    errors += run(path=path, code=code, rootdir=rootdir, options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/core.py", line 36, in run
    linter.run_check(ctx)
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/lint/pylama_pydocstyle.py", line 33, in run_check
    for err in PyDocChecker().check_source(
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/checker.py", line 158, in check_source
    error = this_check(
            ^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/checker.py", line 527, in check_imperative_mood
    and not function.is_property(self.property_decorators)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/parser.py", line 223, in is_property
    return any(
           ^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/parser.py", line 224, in <genexpr>
    decorator.name in property_decorator_names
TypeError: argument of type 'bool' is not iterable
Traceback (most recent call last):
  File "/home/cbm/.local/bin/pylama", line 8, in <module>
    sys.exit(shell())
             ^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/main.py", line 115, in shell
    errors = check_paths(
             ^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/main.py", line 68, in check_paths
    errors += run(path=path, code=code, rootdir=rootdir, options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/core.py", line 36, in run
    linter.run_check(ctx)
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/lint/pylama_pydocstyle.py", line 33, in run_check
    for err in PyDocChecker().check_source(
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/checker.py", line 158, in check_source
    error = this_check(
            ^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/checker.py", line 527, in check_imperative_mood
    and not function.is_property(self.property_decorators)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/parser.py", line 223, in is_property
    return any(
           ^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/parser.py", line 224, in <genexpr>
    decorator.name in property_decorator_names
TypeError: argument of type 'bool' is not iterable

bandit...................................................................Passed
```

- - - -

I'm not sure what `pylama` is but I tried the running it by itself without the `pre-commit` "stuff", and I have a similar error:
```
$ pylama --version
pylama 8.4.1

$ pylama 
Traceback (most recent call last):
  File "/home/cbm/.local/bin/pylama", line 8, in <module>
    sys.exit(shell())
             ^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/main.py", line 115, in shell
    errors = check_paths(
             ^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/main.py", line 68, in check_paths
    errors += run(path=path, code=code, rootdir=rootdir, options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/core.py", line 36, in run
    linter.run_check(ctx)
  File "/home/cbm/.local/lib/python3.11/site-packages/pylama/lint/pylama_pydocstyle.py", line 33, in run_check
    for err in PyDocChecker().check_source(
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/checker.py", line 158, in check_source
    error = this_check(
            ^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/checker.py", line 527, in check_imperative_mood
    and not function.is_property(self.property_decorators)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/parser.py", line 223, in is_property
    return any(
           ^^^^
  File "/home/cbm/.local/lib/python3.11/site-packages/pydocstyle/parser.py", line 224, in <genexpr>
    decorator.name in property_decorator_names
TypeError: argument of type 'bool' is not iterable
```

**Comment by real-yfprojects** [comment]
Install poetry with (although this is not the problem):

```
python3 -m pip install --user pipx
python3 -m pipx ensurepath
pipx install poetry
```

Run pylama:
```
poetry run pylama
```

Run pre-commit (This won't be necessary once #39 is merged):
```
poetry shell
pre-commit run
```

**Comment by johannesjh** [comment]
#39 is merged, @cbm755 does it work for you, shall we close this issue?

**Comment by cbm755** [comment]
Yes, I think it works after #39.
