### ISSUE TITLE
CI breaking with poetry.lock errors

### ISSUE THREAD

**Issue by cbm755** [johannesjh/req2flatpak#72]
```
poetry-check.............................................................Passed
poetry-lock..............................................................Failed
- hook id: poetry-lock
- files were modified by this hook

Resolving dependencies...

Writing lock file

Sync with Poetry.........................................................Passed
isort (python)...........................................................Passed
black....................................................................Passed
prettier.................................................................Passed
rstcheck.................................................................Passed
pylama...................................................................Passed
bandit...................................................................Passed
make: *** [Makefile:7: lint] Error 1
Error: Process completed with exit code 2.
```

I don't see this locally.  But instead I see:

```
pylama...................................................................Failed
- hook id: pylama
- exit code: 1

Traceback (most recent call last):
  File "/home/cbm/.local/bin/pylama", line 8, in <module>
    sys.exit(shell())
             ^^^^^^^
  File "/home/cbm/.local/lib/python3.12/site-packages/pylama/main.py", line 115, in shell
    errors = check_paths(
             ^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.12/site-packages/pylama/main.py", line 68, in check_paths
    errors += run(path=path, code=code, rootdir=rootdir, options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm/.local/lib/python3.12/site-packages/pylama/core.py", line 36, in run
    linter.run_check(ctx)
  File "/home/cbm/.local/lib/python3.12/site-packages/pylama/lint/pylama_pydocstyle.py", line 33, in run_check
    for err in PyDocChecker().check_source(
  File "/usr/lib/python3.12/site-packages/pydocstyle/checker.py", line 158, in check_source
    error = this_check(
            ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pydocstyle/checker.py", line 527, in check_imperative_mood
    and not function.is_property(self.property_decorators)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pydocstyle/parser.py", line 223, in is_property
    return any(
           ^^^^
  File "/usr/lib/python3.12/site-packages/pydocstyle/parser.py", line 224, in <genexpr>
    decorator.name in property_decorator_names
TypeError: argument of type 'bool' is not iterable

bandit...................................................................Passed
```

**Comment by cbm755** [comment]
I think `pylama` might not be maintained...  it seems broken on Python 3.12: https://github.com/klen/pylama/pull/254, https://github.com/klen/pylama/issues/249

AFAICT, pylama is a frontend to a bunch of linters: we might need to use those directly if upstream pylama doesn't make a new release.
